### PR TITLE
Fix compat with other non-boxed middleware

### LINKED ISSUE #60: Compiler error in 0.6.0.beta-3
To reproduce the issue I'm having, create a new crate with the following dependencies (possibly not all required)

```
[dependencies]
actix-web = "4.0.0-beta.8"
actix-cors = "0.6.0-beta.3"
actix-web-prom = "0.6.0-beta.3"
```
It gives the following compiler error:
```
error[E0432]: unresolved imports `actix_web::body::AnyBody`, `actix_web::dev::BodySize`, `actix_web::dev::MessageBody`, `actix_web::http::HeaderValue`
   --> /home/erlend/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-prom-0.6.0-beta.3/src/lib.rs:218:5
    |
218 |     body::AnyBody,
    |     ^^^^^^^^^^^^^ no `AnyBody` in `body`
219 |     dev::{BodySize, MessageBody, Service, ServiceRequest, ServiceResponse, Transform},
    |           ^^^^^^^^  ^^^^^^^^^^^ no `MessageBody` in `dev`
    |           |
    |           no `BodySize` in `dev`
220 |     http::{header::CONTENT_TYPE, HeaderValue, Method, StatusCode},
    |                                  ^^^^^^^^^^^ no `HeaderValue` in `http`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `actix-web-prom` due to previous error
```

rustc:
```
rustc 1.58.0-nightly (dd549dcab 2021-11-25)
```

### PR DESCRIPTION
**Pull request by robjtede**
closes #60

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -447,17 +445,27 @@ where
                     CONTENT_TYPE,
                     HeaderValue::from_static("text/plain; version=0.0.4; charset=utf-8"),
                 );
-                body = BoxBody::new(inner.metrics());
+
+                EitherBody::right(BoxBody::new(StreamLog {
```
Comment (robjtede) [inline src/lib.rs:449]: from the current code, it seems like you still want to wrap this other response type in StreamLog?

File: src/lib.rs [hunk 2]
```diff
@@ -447,17 +445,27 @@ where
...
+                    body: inner.metrics(),
+                    size: 0,
+                    clock: time,
+                    inner,
+                    status: head.status,
+                    path: pattern_or_path,
+                    method,
+                }))
```
Comment (robjtede) [inline src/lib.rs]: From the current code, it seems like you still want to wrap this other response type in StreamLog?
